name = "nocturne"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
vars = { NEXT_PUBLIC_REDIRECT_URI = "https://nocturne.brandons.place", NEXT_PUBLIC_SUPABASE_URL = "https://oagljtsmmhlfswztuvwj.supabase.co", NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZ2xqdHNtbWhsZnN3enR1dndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA0Mzg5NzYsImV4cCI6MjA0NjAxNDk3Nn0.CKLDZnxw4atQ2Sm_e8YBYsMLOLpzA2-FlaX3YloSobM", NEXT_PUBLIC_SPOTIFY_CLIENT_ID = "08390e961b7143718a73dd1b7df34af2" }

[env.preview]
vars = { NEXT_PUBLIC_REDIRECT_URI = "https://main.nocturne-ui.pages.dev", NEXT_PUBLIC_SPOTIFY_CLIENT_ID = "08390e961b7143718a73dd1b7df34af2" }